repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.8.2
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-sphinx
    rev: v4.2.0
    hooks:
      - id: build
        args: ["-b", "html", "docs", "docs/_build/html"]
